version: '3'
services:
  web:
    image: fireantik/spa-prod:latest
    volumes:
      - cra:/app
    environment:
      - SPA_PROD_ROOT=/app/build
      - SPA_PROD_INDEX=/app/build/index.html
    ports:
      - '80:8080'
