image: node:10.13-alpine

stages:
  - install
  - build_test
  - publish

install:
  stage: install
  retry: 2
  variables:
    YARN_CACHE_FOLDER: yarn
  artifacts:
    paths:
      - node_modules/
  cache:
    paths:
      - yarn/
  script:
    - yarn install --pure-lockfile --production=false

test:
  stage: build_test
  dependencies:
    - install
  script: yarn test:coverage
  after_script:
    - './node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov'
    - './node_modules/.bin/codecov'

# audit:
#   stage: build_test
#   allow_failure: true
#   dependencies:
#     - install
#   script: yarn audit

lint:
  stage: build_test
  dependencies:
    - install
  script: yarn lint

typecheck:
  stage: build_test
  dependencies:
    - install
  script: yarn typecheck

build:
  stage: build_test
  dependencies:
    - install
  script: yarn build
  artifacts:
    paths:
      - dist/

build api:
  stage: build_test
  only:
    - master
  dependencies:
    - install
  script: yarn build:api
  artifacts:
    paths:
      - api/

npm publish:
  stage: publish
  only:
    - tags
  dependencies:
    - install
    - build
  script:
    - npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
    - npm publish

api publish:
  image: indiehosters/git
  stage: publish
  only:
    - master
  dependencies:
    - build api
  before_script:
    - git config --global user.email "api@generator"
    - git config --global user.name "API generator"
    - git remote set-url origin git@github.com:jkelin/spa-prod.git
    - mkdir -p ~/.ssh/
    - echo "$API_GENERATOR_SSH" > ~/.ssh/id_rsa
    - echo "$API_GENERATOR_SSH_PUB" > ~/.ssh/id_rsa.pub
    - chmod 600 ~/.ssh/id_rsa
  script:
    - mv api ../api
    - git checkout --orphan gh-pages
    - git reset --hard
    - mv ../api/* ./
    - rm -rf ../api
    - git add -A
    - git commit -m "Generate API docs"
    - git push -f --no-verify origin gh-pages
