language: node_js
node_js:
  - '10'
jobs:
  include:
    - stage: test
      script: yarn test
      after_success:
        - ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
        - ./node_modules/.bin/codecov
    - script: yarn lint
